# .github/workflows/cicd.yaml

name: CICD Nodejs app to Google App Engine
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:
    name: Build Nodejs App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint

  deploy:
    needs: [build]
    #if: github.ref == 'refs/heads/main'
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}        
      - uses: google-github-actions/deploy-appengine@v1
        with:
          credentials_json: $GCP_CREDENTIALS   