# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - domainio-new-app
jobs:

  build:
    name: Build Nodejs App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
    
  deploy:
    needs: [build]
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
       # Set up authentication to google cloud via the service account       
      # - uses: google-github-actions/setup-gcloud@v1
     # - uses: google-github-actions/deploy-appengine@v1
        # with:
        #   credentials: ${{ secrets.GCP_CREDENTIALS }}
        #   export_default_credentials: true
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}        
      - uses: google-github-actions/deploy-appengine@v1
        with:
          credentials_json: $GCP_CREDENTIALS
      # - name: Install node dependencies
      #   run: npm ci
      # - name: Deploy to google cloud
      #   run: |
      #     gcloud config set project turing-reach-373012
      #     gcloud app deploy deploy.yaml --quiet          